import numpy as np
list1 = [1, 2, 3]
print(np.array(list1))
arr = np.array(list1)
print("Array:")
print(arr)
print("Sepuence of n numbers:")
print(np.arange(0, 10))
print("Sequence of n numbers with stepSize 3:")
print(np.arange(0,100,3))
print("Print 5 zeros in Array:")
a=np.zeros(5)
print(a)
print("Print zeros in 3*3 Matrix:")
a=np.zeros((3,3))
print(a)
print("Print 6 one's in 1D Array:")
b=np.ones(6)
print(b)
print("Print 1's in 5*5 Matrix:")
b=np.ones((5,5))
print(b)
c=np.linspace(0,100,40)
print("It divides into 40 equal divisons between 0 to 100 (Incl. both end numbers):")
print(c)
c=np.linspace(0,100,3)
print("It divides from 0 to 100 into 3 equal divisions incl. both ends:")
print(c)
d=np.random.randint(0,100)
print(d)
d=np.random.randint(0,100,(3,3))
print(d)
f=d.max()
print("Maximum Number index:")
print(f)
g=d.min()
print("Minimum number:")
print(g)
h=d.argmax()
print("Maximum number index:")
print(h)
i=d.argmin()
print("Min num index:")
print(i)
np.random.seed(13)
e=np.random.randint(0,50)
print(e)
np.random.seed(100)
v=np.random.randint(1,100,10)
x=v.reshape(5,2)
print(x)
y=v.reshape(2,5)
print(y)
z=np.arange(0,100).reshape(10,10)
print(z)
print(z[4,3])
print(z[:,0])
print(z[1,:])
